// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLP4ItnghJe5Y3UfQlWsHTzZGA3wnmPQQ',
    appId: '1:29388899033:web:674102f39c75bb734834c8',
    messagingSenderId: '29388899033',
    projectId: 'mars-geology',
    authDomain: 'mars-geology.firebaseapp.com',
    storageBucket: 'mars-geology.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7P79ItBbQ3p0L4eAOYbaekVXwwEU9Yi4',
    appId: '1:29388899033:android:7aa4a4e88f9ece0e4834c8',
    messagingSenderId: '29388899033',
    projectId: 'mars-geology',
    storageBucket: 'mars-geology.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9iIfiY-Hq_y4kfbC53J5tvuLUs1vMbUc',
    appId: '1:29388899033:ios:1697ceaa719f13fb4834c8',
    messagingSenderId: '29388899033',
    projectId: 'mars-geology',
    storageBucket: 'mars-geology.appspot.com',
    iosClientId: '29388899033-nelh152e83qprhbr79bs2l4tam78oude.apps.googleusercontent.com',
    iosBundleId: 'com.example.marsgeology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9iIfiY-Hq_y4kfbC53J5tvuLUs1vMbUc',
    appId: '1:29388899033:ios:1697ceaa719f13fb4834c8',
    messagingSenderId: '29388899033',
    projectId: 'mars-geology',
    storageBucket: 'mars-geology.appspot.com',
    iosClientId: '29388899033-nelh152e83qprhbr79bs2l4tam78oude.apps.googleusercontent.com',
    iosBundleId: 'com.example.marsgeology',
  );
}
